### ISSUE TITLE
Requesting more information

### ISSUE THREAD

**Issue by Timohiho** [Arkanic/reimagined-meme#2]
Playing with WebSockets is funny I agree, what are you doing with them rn?

**Comment by Arkanic** [comment]
Making a miniature "game".
Websockets work by sending a HTTP request, and then not closing it, allowing for two-way communication without the HTTP header every time.
Because of this, they send faster than standard POST requests, whilst still allowing you to use TCP.

More specifically, I use websockets so the client (the device you are playing the game on) can communicate with the server (where the actual game logic is processed).

Thanks for taking interest.
